services:
 
  banking-api:
    build:
      context: ./application
    container_name: banking-api-compose
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
 
  postgres:
    image: postgres:16
    container_name: banking-postgres
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: banking_user
      POSTGRES_PASSWORD: banking_pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U banking_user -d banking"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
 
volumes:
  postgres_data:
